# Use postgres/example user/password credentials
version: '3.6'

services:

  db:
    image: postgres:11.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: javapwd
      POSTGRES_USER: java
      POSTGRES_DB: petclinic

  adminer:
    image: adminer:4.7.4
    restart: always
    ports:
      - 8080:8080
