# Use postgres/example user/password credentials
version: '3.6'

services:

  db:
    image: postgres:11.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: djangopwd
      POSTGRES_USER: django
      POSTGRES_DB: django_tutorial
      CHARSET: UTF8
      PGPORT: 5432

  dbtest:
    image: postgres:11.5
    restart: always
    ports:
      - 5464:5464
    environment:
      POSTGRES_PASSWORD: djangopwd
      POSTGRES_USER: django
      POSTGRES_DB: django_tutorial_test
      CHARSET: UTF8
      PGPORT: 5464

  adminer:
    image: adminer:4.7.4
    restart: always
    ports:
      - 8080:8080
